// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-annotate-label'
  | 'pref-api-base-url'
  | 'pref-api-key'
  | 'pref-auto-annotate'
  | 'pref-color-conclusion'
  | 'pref-color-key-finding'
  | 'pref-color-limitation'
  | 'pref-color-methodology'
  | 'pref-help'
  | 'pref-max-tokens'
  | 'pref-min-paragraph-chars'
  | 'pref-model-name'
  | 'pref-openrouter-help'
  | 'pref-title'
  | 'startup-begin'
  | 'startup-finish';
