// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "apiBaseUrl": string;
      "modelName": string;
      "maxTokenThreshold": number;
      "minParagraphChars": number;
      "autoAnnotate": boolean;
      "colorKeyFinding": string;
      "colorMethodology": string;
      "colorConclusion": string;
      "colorLimitation": string;
    };
  }
}
