import type { LLMResponse } from "./llmClient";
import type { ExtractionResult } from "./pdfExtractor";
import { findQuoteInPage } from "./textMatcher";
import { markAsAnnotated } from "./skipCheck";
import { getPref } from "../utils/prefs";

const CATEGORY_COLORS: Record<string, () => string> = {
  key_finding: () => getPref("colorKeyFinding"),
  methodology: () => getPref("colorMethodology"),
  conclusion: () => getPref("colorConclusion"),
  limitation: () => getPref("colorLimitation"),
};
const SUMMARY_NOTE_TITLE = "ZPA Summary";
const SUMMARY_NOTE_MARKER = "Auto-generated by Zotero Paper Annotator";

function getColorForCategory(category: string): string {
  const getter = CATEGORY_COLORS[category];
  return getter ? getter() : getPref("colorKeyFinding");
}

function padNumber(value: number, width: number): string {
  return Math.floor(Math.max(0, value)).toString().padStart(width, "0");
}

function buildPdfSortIndex(
  pageIndex: number,
  rects: Array<[number, number, number, number]>,
  sequence: number,
): string {
  const firstRect = rects[0];
  const top = firstRect ? Math.min(firstRect[1], firstRect[3]) : 0;

  return [
    padNumber(pageIndex, 5).slice(-5),
    padNumber(sequence, 6).slice(-6),
    padNumber(top, 5).slice(-5),
  ].join("|");
}

function generateAnnotationKey(): string {
  const generateKey = (Zotero as any).DataObjectUtilities?.generateKey;
  if (typeof generateKey === "function") {
    return generateKey();
  }
  return Zotero.Utilities.randomString(8);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildSummaryNote(summary: string): string {
  return (
    `<h2>${SUMMARY_NOTE_TITLE}</h2><p>${escapeHtml(summary)}</p>` +
    `<p><em>${SUMMARY_NOTE_MARKER}</em></p>`
  );
}

function isZpaSummaryNote(note: Zotero.Item): boolean {
  const title = note.getNoteTitle();
  const content = note.getNote();

  return (
    title === SUMMARY_NOTE_TITLE ||
    content.includes(`<h2>${SUMMARY_NOTE_TITLE}</h2>`) ||
    content.includes(SUMMARY_NOTE_MARKER)
  );
}

async function findExistingSummaryNote(
  item: Zotero.Item,
): Promise<Zotero.Item | undefined> {
  await item.loadAllData(true);
  const noteIDs = item.getNotes();

  for (const noteID of noteIDs) {
    const note = await Zotero.Items.getAsync(noteID);
    if (isZpaSummaryNote(note)) {
      return note;
    }
  }

  return undefined;
}

async function saveSummaryNote(
  item: Zotero.Item,
  summary: string,
): Promise<{ created: boolean; handled: boolean }> {
  if (summary.trim().length === 0) {
    return { created: false, handled: false };
  }

  const content = buildSummaryNote(summary);
  const existingNote = await findExistingSummaryNote(item);

  if (existingNote) {
    if (existingNote.getNote() !== content) {
      existingNote.setNote(content);
      await existingNote.saveTx();
    }
    return { created: false, handled: true };
  }

  const summaryNote = new Zotero.Item("note");
  summaryNote.parentID = item.id;
  summaryNote.setNote(content);
  await summaryNote.saveTx();

  return { created: true, handled: true };
}

interface AnnotationResult {
  created: number;
  skipped: number;
  summaryNoteCreated: boolean;
}

/**
 * Create Zotero highlight annotations from LLM output.
 */
async function createAnnotations(
  item: Zotero.Item,
  attachmentID: number,
  extraction: ExtractionResult,
  llmResponse: LLMResponse,
  annotatedItem: Zotero.Item = item,
): Promise<AnnotationResult> {
  let created = 0;
  let skipped = 0;
  let attachment: Zotero.Item | undefined;

  if (llmResponse.annotations.length > 0) {
    attachment = await Zotero.Items.getAsync(attachmentID);
    if (!attachment) {
      throw new Error(`Attachment ${attachmentID} not found`);
    }
  }

  for (const ann of llmResponse.annotations) {
    // Pages in LLM response are 1-indexed, pageIndex is 0-indexed
    const pageIndex = ann.page - 1;
    const page = extraction.pages.find((p) => p.pageIndex === pageIndex);

    if (!page) {
      skipped++;
      Zotero.debug(`[ZPA] Page ${ann.page} not found, skipping annotation`);
      continue;
    }

    const rects = findQuoteInPage(ann.quote, page.text, page.items);
    if (!rects || rects.length === 0) {
      skipped++;
      Zotero.debug(
        `[ZPA] Quote not found on page ${ann.page}: "${ann.quote.slice(0, 50)}..."`,
      );
      continue;
    }

    try {
      const annotationJSON = {
        key: generateAnnotationKey(),
        type: "highlight",
        text: ann.quote,
        comment: `[${escapeHtml(ann.category)}] ${escapeHtml(ann.note)}`,
        color: getColorForCategory(ann.category),
        pageLabel: page.pageLabel,
        sortIndex: buildPdfSortIndex(pageIndex, rects, created + skipped),
        position: {
          pageIndex,
          rects,
        },
      };
      await Zotero.Annotations.saveFromJSON(attachment!, annotationJSON as any);
      created++;
    } catch (err) {
      skipped++;
      Zotero.debug(`[ZPA] Error creating annotation: ${err}`);
    }
  }

  // Create or update the item-level summary note
  let summaryNoteCreated = false;
  let summaryNoteHandled = false;
  try {
    const summaryNoteResult = await saveSummaryNote(item, llmResponse.summary);
    summaryNoteCreated = summaryNoteResult.created;
    summaryNoteHandled = summaryNoteResult.handled;
  } catch (err) {
    Zotero.debug(`[ZPA] Error saving summary note: ${err}`);
  }

  // Mark after meaningful output so a processed LLM response is not repeated.
  // If the model requested highlights but every save failed, leave it retryable.
  if (
    created > 0 ||
    (llmResponse.annotations.length === 0 && summaryNoteHandled)
  ) {
    await markAsAnnotated(annotatedItem);
  }

  return { created, skipped, summaryNoteCreated };
}

export { buildPdfSortIndex, createAnnotations, getColorForCategory };
export type { AnnotationResult };
