import type { LLMResponse } from "./llmClient";
import type { ExtractionResult } from "./pdfExtractor";
import { findQuoteInPage } from "./textMatcher";
import { markAsAnnotated } from "./skipCheck";
import { getPref } from "../utils/prefs";

const CATEGORY_COLORS: Record<string, () => string> = {
  key_finding: () => getPref("colorKeyFinding"),
  methodology: () => getPref("colorMethodology"),
  conclusion: () => getPref("colorConclusion"),
  limitation: () => getPref("colorLimitation"),
};

function getColorForCategory(category: string): string {
  const getter = CATEGORY_COLORS[category];
  return getter ? getter() : getPref("colorKeyFinding");
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

interface AnnotationResult {
  created: number;
  skipped: number;
  summaryNoteCreated: boolean;
}

/**
 * Create Zotero highlight annotations from LLM output.
 */
async function createAnnotations(
  item: Zotero.Item,
  attachmentID: number,
  extraction: ExtractionResult,
  llmResponse: LLMResponse,
): Promise<AnnotationResult> {
  let created = 0;
  let skipped = 0;

  for (const ann of llmResponse.annotations) {
    // Pages in LLM response are 1-indexed, pageIndex is 0-indexed
    const pageIndex = ann.page - 1;
    const page = extraction.pages.find((p) => p.pageIndex === pageIndex);

    if (!page) {
      skipped++;
      Zotero.debug(`[ZPA] Page ${ann.page} not found, skipping annotation`);
      continue;
    }

    const rects = findQuoteInPage(ann.quote, page.text, page.items);
    if (!rects || rects.length === 0) {
      skipped++;
      Zotero.debug(
        `[ZPA] Quote not found on page ${ann.page}: "${ann.quote.slice(0, 50)}..."`,
      );
      continue;
    }

    try {
      const annotation = new Zotero.Item("annotation");
      annotation.parentID = attachmentID;
      (annotation as any).annotationType = "highlight";
      (annotation as any).annotationText = ann.quote;
      (annotation as any).annotationComment = `[${escapeHtml(ann.category)}] ${escapeHtml(ann.note)}`;
      (annotation as any).annotationColor = getColorForCategory(ann.category);
      // rects are in PDF user space coordinates [x1, y1, x2, y2] from PDF.js
      (annotation as any).annotationPosition = JSON.stringify({
        pageIndex,
        rects,
      });
      await annotation.saveTx();
      created++;
    } catch (err) {
      skipped++;
      Zotero.debug(`[ZPA] Error creating annotation: ${err}`);
    }
  }

  // Create item-level summary note
  let summaryNoteCreated = false;
  try {
    const summaryNote = new Zotero.Item("note");
    summaryNote.parentID = item.id;
    summaryNote.setNote(
      `<h2>ZPA Summary</h2><p>${escapeHtml(llmResponse.summary)}</p>` +
        `<p><em>Auto-generated by Zotero Paper Annotator</em></p>`,
    );
    await summaryNote.saveTx();
    summaryNoteCreated = true;
  } catch (err) {
    Zotero.debug(`[ZPA] Error creating summary note: ${err}`);
  }

  // Mark item as annotated only when annotations were actually created
  if (created > 0) {
    await markAsAnnotated(item);
  }

  return { created, skipped, summaryNoteCreated };
}

export { createAnnotations, getColorForCategory };
export type { AnnotationResult };
